### ISSUE TITLE
关于论文中的Candidate Elimination

### ISSUE THREAD

**Issue by LeungWaiHo** [botaoye/OSTrack#1]
作者您好，嘿嘿，感谢您的工作，我有些问题关于Candidate Elimination部分
1、我想问下这个candidate指的是search region的每个patch，您也提到了“the attention weights of the search region highlight the foreground objects in the early stage of ViT”，这里的“”attention weights“”指的是“”search为q/template为k时的attention“”
还是“”template为q/search为k时的attention“”？
2、您提到了ω_x决定了template和search的相似度，但在下面又提到“ We average the similarity scores of all heads”中平均的是ω_z，并平均值作为“”serves as the final similarity score of the template and each candidate“”，这是否和前面所述矛盾？

**Comment by botaoye** [comment]
Hi, thanks for the interest.
1. Here ''attention weights'' refers to the weights of the target corresponding to all search region tokens (we use the central token of the template to represent the target during visualization and early candidate elimination), in other words, the ''attention weights'' can be seen as the similarity between the target and each search region token (candidate). You can think of the central token of the template as the query and all search region tokens as the key, but actually there is no difference between the  the identity of the query and the key, since we adopt the concatenated self-attention operation instead of cross-attention.
2. Thanks for pointing it out. This was actually a typo, all ω_z should be ω_x, and we will correct it in our paper.

**Comment by botaoye** [comment]
I will close this issue and if you have any other questions, please feel free to ask.
