### ISSUE TITLE
'out of memory' error with 2080ti

### ISSUE THREAD

**Issue by lawpdas** [botaoye/OSTrack#20]
Hi! 
I noticed that this tracker can be trained on 4*2080Ti.
 I used two 2080ti for training, but there was an out-of-memory error.  Should I change the batch size? How to disable the CE module?

**Comment by botaoye** [comment]
Hi, sorry for the late reply. When testing the training time of the 2080Ti, I removed the warm-up process for early candidate elimination. Since the provided config adds the warm-up step (which means that the early candidate elimination module is not used at the beginning of training), the GPU memory consumption is a bit higher than the 2080Ti GPU memory (13G vs 11G). You can remove the warm-up step, change the batch size, or use mixed precision training to train on the 2080Ti.
