### ISSUE TITLE
search region resolution for OSTrack-256?

### ISSUE THREAD

**Issue by Becomebright** [botaoye/OSTrack#3]
Hi, I noticed some conflicts in your arXiv paper:

- the search region resolution for OSTrack-256 is 256×256 in Section 4.1 but 320 × 320 in Appendix A.
- the search region scale is 5^2 for OSTrack-256 but 4^2 for OSTrack-384.

What are the exact search region resolution and scale?

**Comment by botaoye** [comment]
- The search region resolution for OSTrack-256 is 256×256, 320 in Appendix A is a typo, thanks for pointing it out.
- The search region scale is 4^2 for OSTrack-256 and 5^2 for OSTrack-384, it is not a conflict.

**Comment by Becomebright** [comment]
Thanks for your reply and your amazing work. I have another concern:

OSTrack-384's search region resolution is 384x384, which is 2^2 times larger than that of the template. However, the search scale is 5^2, which is 2.5^2 times larger than the template scale. 

I guess ViT learns to be scale-equivariant and to compensate for the difference. But is there special consideration for such a setting?

**Comment by botaoye** [comment]
Interesting point. The `scale factor` here refers to the expansion of the template/search region (context) corresponding to the area of the target bounding box. Since the scale of the target is constantly changing during tracking, the `resize factor` of the target bounding box in the template and the search region is not necessarily the same even if the ratio of image size and the `scale factor` is kept the same (e.g. in the setting of OSTrack-256). Therefore, we do not intentionally keep the same ratio, and the model is capable to deal with the scale change.
